### PR TITLE
Syncing NESTv2.2.1patch2 to nestpy for v1.4.9

### PR DESCRIPTION
**Pull request by grischbieter**
Merging the changes from NESTv2.2.1patch2
https://github.com/NESTCollaboration/nest/releases/tag/v2.2.1patch2

### CODE REVIEW

**Comment by grischbieter** [comment]
@sophiaandaloro do you have an idea of what's going on here? I was trying to merge the new NEST patch into nestpy (following the same documentation as last time), but I keep getting one of  travis checks failing. I did the commits more piece-wise this time, so I'm wondering if that's the issue. 
I'm thinking of just closing this Merge Request, and starting over with a fresh branch. But I wanted to check with you first in case you see something wrong that I'm missing.

**Comment by sophiaandaloro** [comment]
Taking a look..

**Comment by sophiaandaloro** [comment]
Click on the red X, and follow to the build history on linux. We get the following error message: 
```
Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```
I have already gotten this once before on a build and it seems like we've got some new docker limits. You'll notice your first build from yesterday passed so that's good. I tried to look online and it said we need to increase our docker limit. It's risky to make this merge unless things work on our linux side, so I am hesitant to merge anyway. 
Maybe you know why Docker has been limiting us the last few weeks because I don't? 
I'm tagging @tunnell here because I am off today through Friday, so hopefully he can help now that I've addressed the problem?

**Comment by grischbieter** [comment]
Thanks, I appreciate the early morning help! 
I'm very novice to how these builds work, so I'm hoping @tunnell has some suggestions. I'm definitely confused that things are being flagged on the linux side, because I did my initial tests on a linux machine and things were working as expected. 
If we're limited by the number of build Docker allows us, then I also figure starting fresh on a new branch/attempt won't help... I'll do some more digging on this in the meantime.

**Comment by grischbieter** [comment]
I tried again with a fresh copy on a test branch, but had the same CI failure after committing https://travis-ci.org/github/NESTCollaboration/nestpy/builds/773293272

Doing some research online about pull limits, I followed along from this Docker article to get our pull limits https://www.docker.com/blog/checking-your-current-docker-pull-rate-limits-and-status/ and it appears that I have the "anonymous" requests, with 100 pulls per 6 hours. But this has been about 20 hours since the first instance of this warning from last night, so I'm not sure what the real issue is here. 

Additionally, I compiled nestpy and ran tests on 3 different linux machines (my own, the Albany computing cluster, and a DOE server), and everything worked without errors anywhere. I'm starting to think we should just move forward with the release despite the CI flagging the linux test.

**Comment by grischbieter** [comment]
I did two more tests (hoping that the Docker pull limit would reset) and both resulted in the same issues.

First, I made the a branch and re-tried the NESTv2.2.1patch2 syncing, yesterday morning and got the same issue with only the linux build:
> Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

That branch was "test_sync", with details here https://travis-ci.org/github/NESTCollaboration/nestpy/builds/773384861
So to make sure that this has nothing to do with the new NEST version, I took a clean copy of master (which passed all of the CI tests a few months ago), and committed to a new branch "docker test". This had the exact same issue. So this is solely a problem with Docker/CI. I've tested on 3 different linux machines, and things compile fine and pass all tests. 
So I'm just going to approve the Merge Request and tag the new version! 

>

**Comment by sophiafarrell** [comment]
Thanks @grischbieter for taking care of this while I was away! I am wondering now if we should consider using Docker in the future or move to Github actions, since that has been suggested to me. We can discuss this maybe in Thursday's meeting!

**Pull request merged**
